name: Feature Request
description: "Suggest an idea for this project"
title: "[Feature]: <title>"
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: |
        If applicable, add images/mockups/screenshots to help present your vision of the feature
      description: Drag images into the text input below
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if an issue already exists for the feature you are requesting.
      options:
      - label: I have searched the existing issues
        required: true
